### ISSUE TITLE
missing folders and configuration files

### ISSUE THREAD

**Issue by HoumrS** [DrumSergio/GenieACS-Docker#1] opened 2019-04-15 11:51 UTC
After install missing folders and configuration files:
missing folder: 
/opt/genieacs/
missing files:
/opt/genieacs/config/config.json
/opt/genieacs/config/users.yml

**Comment by DrumSergio** [comment] 2019-04-15 11:55
Hi @HoumrS 

Are you sure you've done it using the provided README?
I have received some emails telling me the same problem and in fact, the problem was people not understanding docker.

Anyway, I would need more info to know what's your exact problem and how can I reproduce it.

**Comment by HoumrS** [comment] 2019-04-15 12:00
Hi 
I folow complete readme from page https://github.com/DrumSergio/GenieACS-Docker

I fond users.yml in :
/var/lib/docker/overlay2/87847d8ca945c7b73771e9f6cbff1c1343d5a6d8a2d97424021885dcf72eb924/merged/opt/genieacs-gui/config/

but config.json missing here

**Comment by DrumSergio** [comment] 2019-04-15 12:09
@HoumrS if you are not connected to the container, you won't see the files.
Your configuration is in fact running, just connect to the IP of the server through HTTP and you'll see it running.

I recommend you to start learning a bit about Docker if you plan on managing this type of configuration.
For example, the command you need to issue is `docker exec -it genieacs /bin/bash` and you will be inside the container. There you can see whatever you need to change.

**Closed** 2019-04-15 12:09 UTC

**Comment by HoumrS** [comment] 2019-04-15 12:19
Thank You, my fault. Im docker newbie. But `docker exec -it genieacs /bin/bash` missing in readme, please add it. It can solve many problems in the future.
SOLVED

**Comment by DrumSergio** [comment] 2019-04-15 12:26
> Thank You, my fault. Im docker newbie. But `docker exec -it genieacs /bin/bash` missing in readme, please add it. It can solve many problems in the future.
> SOLVED

Added it to the README

**Comment by GLENDIS** [comment] 2019-07-01 20:05
Hi.

I already installed the docker and I also made the changes in the files
/opt/genieacs/config/config.json
/opt/genieacs/config/users.yml
Now how can I raise the genieacs-gui?
